"""Domain model."""

from hugin.domain.applications import (
    ApplicationEventRecord,
    ApplicationEventType,
    ApplicationNotFoundError,
    ApplicationRecord,
    ApplicationState,
    DuplicateApplicationError,
    EventPayload,
)
from hugin.domain.content import (
    AnswerSource,
    CompanyRuleType,
    ConfirmationState,
    CoverLetterState,
    DeliveryState,
    IncidentSeverity,
    IncidentState,
    InvitationState,
    MessageDirection,
    NotificationChannel,
    ProfileQuestionState,
    RecruiterMessageState,
    ResumeMappingRole,
    ScreeningFormState,
)
from hugin.domain.directions import (
    AccountRecord,
    ConfigPayload,
    DirectionRecord,
    DirectionVacancyRecord,
    ResumeRecord,
    SearchQueryRecord,
    VacancyState,
)
from hugin.domain.hh import HhApplyResult, HhApplyStatus, HhResumeDetails
from hugin.domain.resumes import (
    ParsedResumeProfile,
    ProfileFactReview,
    ProfileQuestionCandidate,
    ResumeDocument,
    ResumeFactCandidate,
    ResumeImportResult,
    ResumeSourceType,
)
from hugin.domain.state_machines import (
    InvalidStateTransitionError,
    ensure_application_transition,
    ensure_system_transition,
    ensure_task_transition,
)
from hugin.domain.tasks import (
    DuplicateTaskError,
    SystemState,
    SystemStateNotFoundError,
    SystemStateRecord,
    TaskNotFoundError,
    TaskRecord,
    TaskState,
)
from hugin.domain.vacancies import VacancyData, VacancyRecord

__all__ = [
    "AccountRecord",
    "AnswerSource",
    "ApplicationEventRecord",
    "ApplicationEventType",
    "ApplicationNotFoundError",
    "ApplicationRecord",
    "ApplicationState",
    "CompanyRuleType",
    "ConfigPayload",
    "ConfirmationState",
    "CoverLetterState",
    "DeliveryState",
    "DirectionRecord",
    "DirectionVacancyRecord",
    "DuplicateApplicationError",
    "DuplicateTaskError",
    "EventPayload",
    "HhApplyResult",
    "HhApplyStatus",
    "HhResumeDetails",
    "IncidentSeverity",
    "IncidentState",
    "InvalidStateTransitionError",
    "InvitationState",
    "MessageDirection",
    "NotificationChannel",
    "ParsedResumeProfile",
    "ProfileFactReview",
    "ProfileQuestionCandidate",
    "ProfileQuestionState",
    "RecruiterMessageState",
    "ResumeDocument",
    "ResumeFactCandidate",
    "ResumeImportResult",
    "ResumeMappingRole",
    "ResumeRecord",
    "ResumeSourceType",
    "ScreeningFormState",
    "SearchQueryRecord",
    "SystemState",
    "SystemStateNotFoundError",
    "SystemStateRecord",
    "TaskNotFoundError",
    "TaskRecord",
    "TaskState",
    "VacancyData",
    "VacancyRecord",
    "VacancyState",
    "ensure_application_transition",
    "ensure_system_transition",
    "ensure_task_transition",
]
